# Generated by Django 5.2.13 on 2026-04-26 11:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiHaTang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=120, unique=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('la_duong_tuyen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiHaTang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(choices=[('dang_hoat_dong', 'Đang hoạt động'), ('hong_hoc', 'Hỏng hóc'), ('bao_tri', 'Đang bảo trì'), ('ngung_hoat_dong', 'Ngừng hoạt động')], max_length=40, unique=True)),
                ('ten_hien_thi', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HaTang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('vi_tri_diem', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('vi_tri_duong', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('ngay_lap_dat', models.DateField(blank=True, null=True)),
                ('nha_san_xuat', models.CharField(blank=True, max_length=200)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ha_tang', to='assets.loaihatang')),
                ('trang_thai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ha_tang', to='assets.trangthaihatang')),
            ],
        ),
    ]
