# Generated by Django 5.2.13 on 2026-04-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatKyBaoTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('tien_do', models.CharField(choices=[('chua_xu_ly', 'Chưa xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('hoan_thanh', 'Đã hoàn thành')], default='dang_xu_ly', max_length=20)),
                ('ngay_bao_tri', models.DateTimeField(auto_now_add=True)),
                ('ha_tang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhat_ky_bao_tri', to='assets.hatang')),
            ],
        ),
    ]
