# Generated by Django 5.2.13 on 2026-04-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkybaotri',
            name='ky_thuat_vien',
            field=models.ForeignKey(limit_choices_to={'vai_tro': 'technical'}, on_delete=django.db.models.deletion.CASCADE, related_name='nhat_ky_ky_thuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhatkybaotri',
            name='su_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhat_ky', to='incidents.baocaosuco'),
        ),
    ]
