# Generated by Django 5.2.13 on 2026-04-26 11:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoSuCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='su_co/')),
                ('vi_tri', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('muc_do', models.CharField(choices=[('thap', 'Thấp'), ('trung_binh', 'Trung bình'), ('cao', 'Cao'), ('khan_cap', 'Khẩn cấp')], default='trung_binh', max_length=20)),
                ('trang_thai', models.CharField(choices=[('chua_xu_ly', 'Chưa xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('da_hoan_thanh', 'Đã hoàn thành')], default='chua_xu_ly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ha_tang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='su_co', to='assets.hatang')),
            ],
        ),
    ]
