# Generated by Django 5.2.13 on 2026-04-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baocaosuco',
            name='nguoi_bao_cao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_cao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baocaosuco',
            name='nhan_vien_ky_thuat',
            field=models.ForeignKey(blank=True, limit_choices_to={'vai_tro': 'technical'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='su_co_duoc_giao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baocaosuco',
            name='xac_nhan_boi',
            field=models.ForeignKey(blank=True, limit_choices_to={'vai_tro': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='su_co_xac_nhan', to=settings.AUTH_USER_MODEL),
        ),
    ]
